openapi: 3.0.1
info:
  title: Controle
  description: Controle de orçamento
  version: 1.0.0
paths:
  /receitas:
    get:
      summary: Recuperar receitas
      operationId: getReceitas
      tags:
        - Receitas
      parameters:
        - $ref: '#/components/parameters/descricao'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceitasResponse'
    post:
      summary: Inserir uma receita
      operationId: addReceita
      tags:
        - Receitas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceitaDTO'
        required: true
      responses:
        201:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceitaDTO'

  /receitas/{id}:
    get:
      summary: Recuperar receita
      operationId: getReceita
      tags:
        - Receitas
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceitaDTO'

    put:
      summary: Atualizar receita
      operationId: AtualizarReceita
      tags:
        - Receitas
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceitaDTO'
      responses:
        202:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceitaDTO'

    delete:
      summary: Deletar receita
      operationId: DeleteReceita
      tags:
        - Receitas
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        202:
          description: sucesso

  /receitas/{mes}/{ano}:
    get:
      summary: Recuperar receitas do mês
      operationId: getReceitasMensal
      tags:
        - Receitas
      parameters:
        - $ref: '#/components/parameters/mes'
        - $ref: '#/components/parameters/ano'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceitasResponse'

  /despesas:
    get:
      summary: Recuperar despesas
      operationId: getDespesas
      tags:
        - Despesas
      parameters:
        - $ref: '#/components/parameters/descricao'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DespesasResponse'
    post:
      summary: Inserir uma receita
      operationId: addDespesa
      tags:
        - Despesas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DespesaDTO'
        required: true
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DespesaDTO'

  /despesas/{id}:
    get:
      summary: Recuperar despesa
      operationId: getDespesa
      tags:
        - Despesas
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DespesaDTO'

    put:
      summary: Atualizar despesa
      operationId: AtualizarDespesa
      tags:
        - Despesas
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DespesaDTO'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DespesaDTO'

    delete:
      summary: Deletar despesa
      operationId: DeleteDespesa
      tags:
        - Despesas
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        202:
          description: sucesso

  /despesas/{mes}/{ano}:
    get:
      summary: Recuperar despesas do mês
      operationId: getDespesasMensal
      tags:
        - Despesas
      parameters:
        - $ref: '#/components/parameters/mes'
        - $ref: '#/components/parameters/ano'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DespesasResponse'

  /resumos/{mes}/{ano}:
    get:
      summary: Resumo das operações do mês
      operationId: resumoMensal
      tags:
        - Resumos
      parameters:
        - $ref: '#/components/parameters/mes'
        - $ref: '#/components/parameters/ano'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumoResponse'

  /login:
    post:
      summary: Efetuar Login
      operationId: efetuarLogin
      tags:
        - Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DadosAutenticacao'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'



components:
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: string

    mes:
      in: path
      name: mes
      required: true
      schema:
        type: integer

    ano:
      in: path
      name: ano
      required: true
      schema:
        type: integer

    descricao:
      in: query
      name: descricao
      required: false
      schema:
        type: string

  schemas:

    TokenResponse:
      type: object
      properties:
        token:
          type: string

    ReceitasResponse:
      type: object
      properties:
        receitas:
          type: array
          items:
            $ref: '#/components/schemas/ReceitaDTO'

    ReceitaDTO:
      type: object
      properties:
        id:
          type: string
          format: int64
        descricao:
          type: string
          example: Descricao da receita
        valor:
          type: number
        data:
          type: string
          format: 'date-time'


    DespesasResponse:
      type: object
      properties:
        despesas:
          type: array
          items:
            $ref: '#/components/schemas/DespesaDTO'

    DespesaDTO:
      type: object
      properties:
        id:
          type: string
          format: int64
        descricao:
          type: string
          example: Descricao da despesa
        valor:
          type: number
        data:
          type: string
          format: 'date-time'
        categoria:
          $ref: '#/components/schemas/Categoria'

    Categoria:
      type: string
      x-enum-varnames: [ ALIMENTACAO, SAUDE, MORADIA, TRANSPORTE, EDUCACAO, LAZER, IMPREVISTOS, OUTRAS ]
      enum: [ "Alimentação", "Saúde", "Moradia", "Transporte", "Educação", " Lazer", "Imprevistos", "Outras" ]

    ResumoResponse:
      type: object
      properties:
        totalReceita:
          type: number
          example: 100
        totalDespesa:
          type: number
          example: 50
        saldoFinal:
          type: number
          example: 50
        valorCategoria:
          type: array
          items:
            $ref: '#/components/schemas/ResumoCategoria'

    ResumoCategoria:
      type: object
      properties:
        categoria:
          $ref: '#/components/schemas/Categoria'
        valor:
          type: number
          example: 10

    DadosAutenticacao:
      type: object
      properties:
        login:
          type: string
        senha:
          type: string
